// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"matsukana.cloud/go-marketing/config"
	"matsukana.cloud/go-marketing/controller"
	"matsukana.cloud/go-marketing/database"
	"matsukana.cloud/go-marketing/repository"
	"matsukana.cloud/go-marketing/router"
	"matsukana.cloud/go-marketing/service"
)

// Injectors from injector.go:

func InitializedServer() *App {
	configConfig := config.New()
	databaseDatabase := database.New(configConfig)
	app := NewApp(configConfig, databaseDatabase)
	return app
}

func InitializedRouter(Db *database.Database) *fiber.App {
	marketingEventRepositoryImpl := repository.NewMarketingEventRepository()
	marketingEventServiceImpl := service.NewMarketingEventService(Db, marketingEventRepositoryImpl)
	marketingEventControllerImpl := controller.NewMarketingEventController(marketingEventServiceImpl)
	marketingLeadRepositoryImpl := repository.NewMarketingLeadRepository()
	marketingLeadServiceImpl := service.NewMarketingLeadService(Db, marketingLeadRepositoryImpl)
	marketingLeadControllerImpl := controller.NewMarketingLeadController(marketingLeadServiceImpl)
	app := router.New(marketingEventControllerImpl, marketingLeadControllerImpl)
	return app
}

// injector.go:

var MarketingEventSet = wire.NewSet(repository.NewMarketingEventRepository, service.NewMarketingEventService, controller.NewMarketingEventController, wire.Bind(new(repository.MarketingEventRepository), new(*repository.MarketingEventRepositoryImpl)), wire.Bind(new(service.MarketingEventService), new(*service.MarketingEventServiceImpl)), wire.Bind(new(controller.MarketingEventController), new(*controller.MarketingEventControllerImpl)))

var MarketingLeadSet = wire.NewSet(repository.NewMarketingLeadRepository, service.NewMarketingLeadService, controller.NewMarketingLeadController, wire.Bind(new(repository.MarketingLeadRepository), new(*repository.MarketingLeadRepositoryImpl)), wire.Bind(new(service.MarketingLeadService), new(*service.MarketingLeadServiceImpl)), wire.Bind(new(controller.MarketingLeadController), new(*controller.MarketingLeadControllerImpl)))
