// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"matsukana.cloud/go-marketing/config"
	"matsukana.cloud/go-marketing/controller"
	"matsukana.cloud/go-marketing/database"
	"matsukana.cloud/go-marketing/repository"
	"matsukana.cloud/go-marketing/router"
	"matsukana.cloud/go-marketing/service"
)

// Injectors from injector.go:

func InitializedServer() *App {
	configConfig := config.New()
	databaseDatabase := database.New(configConfig)
	app := NewApp(configConfig, databaseDatabase)
	return app
}

func InitializedRouter() *fiber.App {
	configConfig := config.New()
	databaseDatabase := database.New(configConfig)
	marketingEventRepositoryImpl := repository.NewMarketingEventRepository(databaseDatabase)
	marketingEventServiceImpl := service.NewMarketingEventService(databaseDatabase, marketingEventRepositoryImpl)
	marketingEventControllerImpl := controller.NewMarketingEventController(marketingEventServiceImpl)
	marketingLeadRepositoryImpl := repository.NewMarketingLeadRepository(databaseDatabase)
	marketingLeadServiceImpl := service.NewMarketingLeadService(databaseDatabase, marketingLeadRepositoryImpl)
	marketingLeadControllerImpl := controller.NewMarketingLeadController(marketingLeadServiceImpl)
	app := router.New(marketingEventControllerImpl, marketingLeadControllerImpl)
	return app
}

// injector.go:

var MarketingEventSet = wire.NewSet(repository.NewMarketingEventRepository, wire.Bind(new(repository.MarketingEventRepository), new(*repository.MarketingEventRepositoryImpl)), service.NewMarketingEventService, wire.Bind(new(service.MarketingEventService), new(*service.MarketingEventServiceImpl)), controller.NewMarketingEventController, wire.Bind(new(controller.MarketingEventController), new(*controller.MarketingEventControllerImpl)))

var MarketingLeadSet = wire.NewSet(repository.NewMarketingLeadRepository, wire.Bind(new(repository.MarketingLeadRepository), new(*repository.MarketingLeadRepositoryImpl)), service.NewMarketingLeadService, wire.Bind(new(service.MarketingLeadService), new(*service.MarketingLeadServiceImpl)), controller.NewMarketingLeadController, wire.Bind(new(controller.MarketingLeadController), new(*controller.MarketingLeadControllerImpl)))
